doctrine_migrations:
    em: default
    check_database_platform: false
    # Run all migrations in a transaction.
    all_or_nothing: true
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    storage:
        # Default (SQL table) metadata storage configuration
        table_storage:
            table_name: 'MigrationVersions'
            version_column_name: 'version'
            version_column_length: 125
            executed_at_column_name: 'executedAt'
            execution_time_column_name: 'executionTime'
    organize_migrations: 'BY_YEAR'
    services:
        'Doctrine\Migrations\Version\MigrationFactory': 'App\Utils\DBAL\Migrations\MigrationFactoryDecorator'
