nelmio_api_doc:
  documentation:
    info:
      title: MOVIES BACKEND
      description: API documentation
      version: 3.27.6

    components:
      securitySchemes:
        bearerAuth:            # arbitrary name for the security scheme
          type: http
          scheme: bearer
          bearerFormat: JWT    # optional, arbitrary value for documentation purposes
      schemas:
        DefaultResponse:
          properties:
            status:
              type: boolean
            data:
              oneOf:
                - type: boolean
                - type: object
                - type: 'null'
                - type: array
                  items:
                    type: string

      responses:
        200DefaultResponse:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponse'
    security:
      - bearerAuth: []

  areas: # to filter documented areas
    default:
      path_patterns: [ ^/api(?!/docs$)(?!/docs.json$)(?!/docs.yaml)(?!/docs/{area}$)(?!/bot) ]
