framework:
    rate_limiter:
        anonymous_api:
            # use 'sliding_window' if you prefer that policy
            policy: 'fixed_window'
            limit: 100
            interval: '60 seconds'
        authenticated_api:
            policy: 'token_bucket'
            limit: 1500
            rate: { interval: '1 minute', amount: 500 }