# Expose your documentation as JSON swagger compliant
app.swagger:
    path: /api/docs.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

app.swagger_yaml:
    path: /api/docs.yaml
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_yaml }
