monolog:
    handlers:
        main:
            type: rotating_file
            max_files: 2
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
            channels: ["!event"]
        deprecation:
            type: rotating_file
            max_files: 2
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
